Add IT, FR, NL and KR translations
vtex-apps/rich-text pull request #62
Opened 2021-04-30 18:13 UTC by daniserejo

#### What problem is this solving?

Add IT, FR, NL and KR translations and update crowdin and changelog.

#### How to test it?

https://french--storecomponents.myvtex.com/admin
https://dutch--storecomponents.myvtex.com/admin
https://korean--storecomponents.myvtex.com/admin
https://italian--storecomponents.myvtex.com/admin

2021-04-30 19:40 UTC, camilavcoutinho requested changes

2021-04-30 19:40 UTC, camilavcoutinho commented on CHANGELOG.md
> +### Changed
I think it is better to keep that as it was
```suggestion
### Fixed
```

2021-05-03 20:36 UTC, klzns approved these changes

2021-05-04 14:34 UTC, victorhmp approved these changes

2021-05-04 19:24 UTC, camilavcoutinho approved these changes

2021-05-05 12:30 UTC, merged